# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User

bind = Ctrl+Super, Slash, exec, nvim ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, nvim ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

##! security
bind = Super, P, exec, sh -c 'keepassxc & wl-copy < <(tr -d "\n" < ~/.keys/keepassxcKey.txt); sleep 2;cliphist wipe ;wl-copy "Fuck you !"' # KeepassXC Password Manager

# Add stuff here

# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

