# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
# KeePassXC always floating
# KeePassXC always floating
windowrulev2 = float, class:^(org.keepassxc.KeePassXC)$
windowrulev2 = center, class:^(org.keepassxc.KeePassXC)$
windowrulev2 = size 500 550, class:^(org.keepassxc.KeePassXC)$
windowrulev2 = pin, class:^(org.keepassxc.KeePassXC)$
